server:
  port: 8080

spring:
  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/final_project_v2
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: